FROM node:alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}


COPY package.json src/
COPY pm2.json src/

WORKDIR /src

RUN npm install

RUN npm install pm2 -g

WORKDIR /
COPY . src/
WORKDIR /src

CMD [ "pm2-runtime", "start", "pm2.json" ]
